CONN prod/pass@XEPDB1;

create table city (id number(19,0) generated by default as identity, name varchar2(255 char), country_id number(19,0), primary key (id));
create table country (id number(19,0) generated by default as identity, name varchar2(255 char), primary key (id));
create table home (id number(19,0) generated by default as identity, associated_to varchar2(255 char), name varchar2(255 char), city_id number(19,0), primary key (id));
create table iot_gateway (machine_id varchar2(255 char) not null, friendly_name varchar2(255 char), paired_to varchar2(255 char), type number(10,0), home_id number(19,0), primary key (machine_id));
create table record (id number(19,0) generated by default as identity, record_date timestamp, value double precision not null, sensor_id number(19,0), primary key (id));
create table room (id number(19,0) generated by default as identity, name varchar2(255 char), home_id number(19,0), primary key (id));
create table sensor (id number(19,0) generated by default as identity, description varchar2(255 char), name varchar2(255 char), gateway_id varchar2(255 char), room_id number(19,0), primary key (id));
alter table home add constraint UK_6jle5h3iwlmvw52k17oq4o9f8 unique (associated_to);
alter table city add constraint FKrpd7j1p7yxr784adkx4pyepba foreign key (country_id) references country;
alter table home add constraint FK66hpnxjasc2tppt89mvbd5i6r foreign key (city_id) references city;
alter table iot_gateway add constraint FKjlf6g4mjd1nu3vorep743hx2b foreign key (home_id) references home;
alter table record add constraint FK6u79h06y3wcw5w05ywmtfxsdm foreign key (sensor_id) references sensor;
alter table room add constraint FK5otesw2xwna7sly96g1n5l7ob foreign key (home_id) references home;
alter table sensor add constraint FKsa7ho6q36k3jbjw3r69xgfkcf foreign key (gateway_id) references iot_gateway;
alter table sensor add constraint FK109soutvg0bm293dos5nsawxy foreign key (room_id) references room;

insert into country(name) values ('Romania');
insert into country(name) values ('Moldova');
insert into country(name) values ('United Kingdom');
insert into country(name) values ('Mexico');
insert into city(name, country_id) values ('Bucharest', 1);
insert into city(name, country_id) values ('Timisoara', 2);
insert into city(name, country_id) values ('Cluj', 3);
insert into city(name, country_id) values('Chisinau', 2);
insert into city(name, country_id) values('London', 3);
insert into city(name, country_id) values('Mexico City', 4);
