server:
  port: 8082

auth0:
  audience: http://localhost:8080/db/

nn:
  uri: http://localhost:5000

spring:
  application:
    name: mlapp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dissertationuaa.eu.auth0.com/
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: prod_dw
    password: pass
#  jpa:
#    show_sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source: metadata
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    enabled: false

