spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: file:///C:/School/delia/dissertation/configs

server:
  port: 8800