version: '3.9'
services:
  oradb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    networks:
      - db-net
    volumes:
      - ./scripts:/opt/oracle/scripts/startup
    ports:
      - "1521:1521"
networks:
  db-net:
volumes:
  db-vol:
